Billiard-web/src/Billiard/Controllers/DynamicPermissionsSampleController.cs
using System.ComponentModel;
using Billiard.Services.Identity;
using Billiard.ViewModels.Identity;
using DNTBreadCrumb.Core;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Billiard.Controllers
{
    /// <summary>
    /// More info: http://www.dotnettips.info/post/2581
    /// </summary>
    [Authorize(Policy = ConstantPolicies.DynamicPermission)]
    [BreadCrumb(UseDefaultRouteUrl = true, Order = 0)]
    [DisplayName("کنترلر نمونه با سطح دسترسی پویا")]
    public class DynamicPermissionsSampleController : Controller
    {
        [DisplayName("ایندکس")]
        [BreadCrumb(Order = 1)]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Index(RoleViewModel model)
        {
            return View(model);
        }

        [DisplayName("گزارش از لیست کتاب‌ها")]
        [BreadCrumb(Order = 1)]
        public IActionResult Books()
        {
            return View(viewName: "Index");
        }

        [DisplayName("گزارش از لیست مراجعان")]
        [BreadCrumb(Order = 1)]
        public IActionResult Users()
        {
            return View(viewName: "Index");
        }

        [DisplayName("گزارش از لیست امانات")]
        [BreadCrumb(Order = 1)]
        public IActionResult BooksGiven()
        {
            return View(viewName: "Index");
        }

        [DisplayName("گزارش از لیست مفقودی‌ها")]
        [BreadCrumb(Order = 1)]
        public IActionResult BooksMissings()
        {
            return View(viewName: "Index");
        }
    }
}

Billiard-web/src/Billiard/Controllers/DynamicPermissionsTestController.cs
using Billiard.Services.Identity;
using DNTBreadCrumb.Core;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel;
using Billiard.ViewModels.Identity;

namespace Billiard.Controllers
{
    /// <summary>
    /// More info: http://www.dotnettips.info/post/2581
    /// </summary>
    [Authorize(Policy = ConstantPolicies.DynamicPermission)]
    [BreadCrumb(UseDefaultRouteUrl = true, Order = 0)]
    [DisplayName("کنترلر آزمایشی با سطح دسترسی پویا")]
    // [NoBrowserCache]
    public class DynamicPermissionsTestController : Controller
    {
        [DisplayName("ایندکس")]
        [BreadCrumb(Order = 1)]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost] // More info: http://www.dotnettips.info/post/2468/ and http://www.dotnettips.info/post/2470/
        public IActionResult Index([FromBody]RoleViewModel model)
        {
            return Json(model);
        }

        [DisplayName("گزارش از لیست محصولات")]
        [BreadCrumb(Order = 1)]
        public IActionResult Products()
        {
            return View(viewName: "Index");
        }

        [DisplayName("گزارش از لیست سفارشات")]
        [BreadCrumb(Order = 1)]
        public IActionResult Orders()
        {
            return View(viewName: "Index");
        }

        [DisplayName("گزارش از لیست فروش")]
        [BreadCrumb(Order = 1)]
        public IActionResult Sells()
        {
            return View(viewName: "Index");
        }

        [DisplayName("گزارش از لیست خریداران")]
        [BreadCrumb(Order = 1)]
        public IActionResult Customers()
        {
            return View(viewName: "Index");
        }
    }
}

Billiard-web/src/Billiard/Controllers/MessagesController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Billiard.Controllers
{
    public class MessagesController : Controller
    {
        private NotificationsMessageHandler _notificationsMessageHandler { get; set; }

        public MessagesController(NotificationsMessageHandler notificationsMessageHandler)
        {
            _notificationsMessageHandler = notificationsMessageHandler;
        }

        [HttpGet]
        public async Task SendMessage([FromQueryAttribute]string message)
        {
           await _notificationsMessageHandler.SendMessageToAllAsync(message);
        }
    }
}

Billiard-web/src/Billiard/Views/Shared/AccessDenied.cshtml
@{
    ViewData["Title"] = "عدم دسترسی!";
    //this.Context.Response.StatusCode = (int)HttpStatusCode.Unauthorized;
 
    Layout = "_LayoutAuth";
}

    <div class="pt-lg-10 text-center">

        <h1 class="fw-bolder fs-4x text-gray-700 mb-10">مجوز دسترسی</h1>

        <div class="fw-bold fs-3 text-gray-400 mb-15"> متاسفانه شما مجوز دسترسی به صفحه‌ی درخواستی را ندارید.
             <br>به صفحه اصلی بروید
        </div>

           
      

        <div class="text-center">
            <a asp-action="Index" asp-controller="Home" asp-area="" class="btn btn-lg btn-primary fw-bolder">رفتن به صفحه اصلی</a>
        </div>
    </div>


 

Billiard-web/src/Billiard/Views/Shared/NotFound.cshtml
@{
    ViewData["Title"] = "یافت نشد!";
    this.Context.Response.StatusCode = (int)HttpStatusCode.Gone; 
 
    Layout = "_LayoutAuth";
}

    <div class="pt-lg-10 text-center">

        <h1 class="fw-bolder fs-4x text-gray-700 mb-10">اطلاعات درخواستی یافت نشد.</h1>

        <div class="fw-bold fs-3 text-gray-400 mb-15">صفحه ای که به دنبال آن هستید پیدا نشد!
            <br>به صفحه اصلی بروید
        </div>

        <div class="text-center">
            <a asp-action="Index" asp-controller="Home" asp-area="" class="btn btn-lg btn-primary fw-bolder">رفتن به صفحه اصلی</a>
        </div>
    </div>

Billiard-web/src/Billiard/Views/Shared/_CustomValidationSummary.cshtml
@if (ViewData.ModelState.Any(keyValuePair => keyValuePair.Value.Errors.Any() ))
{

 <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <div asp-validation-summary="All"></div>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>}

Billiard-web/src/Billiard/Views/Shared/_DateScript.cshtml
<script src="~/js/vue.Billiard.js" asp-append-version="true"></script>
<script src="~/js/datepicker/moment.min.js"></script>
<script src="~/js/datepicker/moment-jalaali.js"></script>
<script src="~/js/datepicker/vue3-persian-datetime-picker.umd.min.js"></script>

Billiard-web/src/Billiard/Views/Shared/_LayoutAuth.cshtml
@{ var pageTitle = ViewData["Title"] ?? "باشگاه بیلیارد سناتور"; }


<html direction="rtl" dir="rtl" style="direction: rtl">
<head>
     <meta charset="utf-8" />
    <title>@pageTitle</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="shortcut icon" href="~/theme/Desktop/assets/media/logos/favicon.ico" />
    <link href="~/theme/Desktop/assets/plugins/global/plugins.bundle.rtl.css" rel="stylesheet" type="text/css" asp-append-version="true"/>
    <link href="~/theme/Desktop/assets/css/style.bundle.rtl.css" rel="stylesheet" type="text/css" asp-append-version="true"/>
    <link href="~/css/CustomPublic.css" rel="stylesheet" asp-append-version="true"/>
</head>
<body id="ppc_body" class="bg-white">
        
<div id="loader-page">
    <div class="loader" id="line">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
    </div>
</div>
    <div class="d-flex flex-column flex-root">
        <div class="d-flex flex-column flex-column-fluid bgi-position-y-bottom position-x-center bgi-no-repeat bgi-size-contain bgi-attachment-fixed" style="background-image: url(/theme/Desktop/assets/media/illustrations/progress-hd.png)">
            <div class="d-flex flex-center flex-column flex-column-fluid p-10 pb-lg-20">
                <a asp-action="Index" asp-controller="Home" asp-area="" class="mb-12">
                    <img alt="Logo" src="~/theme/Desktop/assets/media/logos/logo-default-dark.png" class="h-45px" />
                </a>
                @RenderBody()

            </div>
            <div class="d-flex flex-center flex-column-auto p-10">
                <div class="d-flex align-items-center fw-bold fs-6">
                    <a href="#" class="text-muted text-hover-primary px-2" target="_blank">درباره ی ما</a>
                    <a href="#" class="text-muted text-hover-primary px-2" target="_blank">پشتیبانی</a>
                    <a href="#" class="text-muted text-hover-primary px-2" target="_blank">تماس با ما</a>
                </div>
            </div>
        </div>
    </div>
    <script src="~/theme/Desktop/assets/plugins/global/plugins.bundle.js"></script>
    <script src="~/theme/Desktop/assets/js/scripts.bundle.js"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <script>

            @* var x = window.location.host+"/Mobile/Home/Index";
                SA.redirection_mobile({
                    tablet_redirection: "true",
                    mobile_url: x,
                    mobile_prefix: "https"
                }); *@
    </script>
</body>
</html>

Billiard-web/src/Billiard/Views/Shared/_Message.cshtml
@model AlertMessageViewModel
<script>
    $.bootstrapModalAlert({
        caption: '@Model.MessageTitle',
        body: '<div class="alert alert-@Model.MessageType"> <span class="bi bi-bell m-5" aria-hidden="true"></span>@Model.MessageText</div>'
    });
    setTimeout(function () {
        $('.modal').modal('hide');
        if (@Model.IsRefreshPage)
        {
            window.location.reload();
        }
    }, 2000);
</script>

Billiard-web/src/Billiard/Views/Shared/_ReportsMenu.cshtml
<div class="navbar-nav">
    <div class="dropdown">
        <a class="nav-item nav-link dropdown-toggle" data-toggle="dropdown"
           id="reportsDropdown" aria-haspopup="true"
           aria-expanded="false" href="#">
            گزارشات نمونه
        </a>
        <div class="dropdown-menu" aria-labelledby="reportsDropdown">
            <security-trimming asp-area="" asp-controller="DynamicPermissionsTest" asp-action="Products">
                    <a class="dropdown-item" asp-controller="DynamicPermissionsTest" asp-action="Products" asp-area="">
                        <span class="mr-1 fas fa-user" aria-hidden="true"></span>
                        گزارش از لیست محصولات
                    </a>
            </security-trimming>

            <security-trimming asp-area="" asp-controller="DynamicPermissionsTest" asp-action="Orders">
                    <a class="dropdown-item" asp-controller="DynamicPermissionsTest" asp-action="Orders" asp-area="">
                        <span class="mr-1 fas fa-cog" aria-hidden="true"></span>
                        گزارش از لیست سفارشات
                    </a>
            </security-trimming>

            <security-trimming asp-area="" asp-controller="DynamicPermissionsTest" asp-action="Sells">
                    <a class="dropdown-item" asp-controller="DynamicPermissionsTest" asp-action="Sells" asp-area="">
                        <span class="mr-1 fas fa-asterisk" aria-hidden="true"></span>
                        گزارش از لیست فروش
                    </a>
            </security-trimming>

            <security-trimming asp-area="" asp-controller="DynamicPermissionsTest" asp-action="Customers">
                    <a class="dropdown-item" asp-controller="DynamicPermissionsTest" asp-action="Customers" asp-area="">
                        <span class="mr-1 fas fa-sign-out-alt" aria-hidden="true"></span>
                        گزارش از لیست خریداران
                    </a>
            </security-trimming>

            <div class="dropdown-divider"></div>

            <security-trimming asp-area="" asp-controller="DynamicPermissionsSample" asp-action="Books">
                    <a class="dropdown-item" asp-controller="DynamicPermissionsSample" asp-action="Books" asp-area="">
                        <span class="mr-1 fas fa-user" aria-hidden="true"></span>
                        گزارش از لیست کتاب‌ها
                    </a>
            </security-trimming>

            <security-trimming asp-area="" asp-controller="DynamicPermissionsSample" asp-action="Users">
                    <a class="dropdown-item" asp-controller="DynamicPermissionsSample" asp-action="Users" asp-area="">
                        <span class="mr-1 fas fa-cog" aria-hidden="true"></span>
                        گزارش از لیست مراجعان
                    </a>
            </security-trimming>

            <security-trimming asp-area="" asp-controller="DynamicPermissionsSample" asp-action="BooksGiven">
                    <a class="dropdown-item" asp-controller="DynamicPermissionsSample" asp-action="BooksGiven" asp-area="">
                        <span class="mr-1 fas fa-asterisk" aria-hidden="true"></span>
                        گزارش از لیست امانات
                    </a>
            </security-trimming>

            <security-trimming asp-area="" asp-controller="DynamicPermissionsSample" asp-action="BooksMissings">
                    <a class="dropdown-item" asp-controller="DynamicPermissionsSample" asp-action="BooksMissings" asp-area="">
                        <span class="mr-1 fas fa-sign-out-alt" aria-hidden="true"></span>
                        گزارش از لیست مفقودی‌ها
                    </a>
            </security-trimming>
        </div>
    </div>
</div>

Billiard-web/src/Billiard/Views/Shared/_SidebarMenu.cshtml
<div id="OnlineUsers" dir="rtl">
    <cache expires-after="@TimeSpan.FromMinutes(1)">
        <vc:online-users numbers-to-take="5" minutes-to-take="5" show-more-items-link="true"></vc:online-users>
    </cache>
</div>

<div id="TodayBirthDays" dir="rtl">
    <cache expires-after="@TimeSpan.FromMinutes(5)">
        <vc:today-birth-days></vc:today-birth-days>
    </cache>
</div>

Billiard-web/src/Billiard/Views/Shared/_UserMenu.cshtml
@inject IUsersPhotoService PhotoService

@{
    var displayName = User.Identity.GetUserDisplayName();
    var username = User.Identity.GetUserName();
    var photoUrl = PhotoService.GetCurrentUserPhotoUrl(); 
}


<div class="d-flex align-items-center ms-1 ms-lg-3" id="ppc_header_user_menu_toggle">
    <div class="cursor-pointer symbol symbol-30px symbol-md-40px" data-ppc-menu-trigger="click"
        data-ppc-menu-attach="parent" data-ppc-menu-placement="bottom-end" data-ppc-menu-flip="bottom">

        <img class="iconimg" src="@photoUrl" alt="@displayName" />

    </div>
    @if (User.Identity.IsAuthenticated)
    {
        <div class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-600 menu-state-bg-light-primary fw-bold py-4 fs-6 w-275px"
        data-ppc-menu="true">
            <div class="menu-item px-3">
                <div class="menu-content d-flex align-items-center px-3">
                    <div class="symbol symbol-50px me-5">
                        <img alt="@displayName" src="@photoUrl" />
                    </div>
                    <div class="d-flex flex-column">
                        <div class="fw-bolder d-flex align-items-center fs-5">
                            @displayName
                        </div>
                        <a href="#" class="fw-bold text-muted text-hover-primary fs-7">@username</a>
                    </div>
                </div>
            </div>
            <div class="separator my-2"></div>
            <div class="menu-item px-5">
                <a class="menu-link px-5" asp-controller="User" asp-action="Index" asp-area="@AreaConstants.DashboardArea">
                    صفحه شخصی شما
                </a>
            </div>
            <div class="menu-item px-5">
                <a class="menu-link px-5" asp-controller="UserProfile" asp-action="Index"
                asp-area="@AreaConstants.DashboardArea">
                    تنظیمات حساب کاربری
                </a>
            </div>
            <div class="menu-item px-5 my-1">
                <a class="menu-link px-5" asp-controller="ChangePassword" asp-action="Index"
                asp-area="@AreaConstants.DashboardArea">
                    تغییر کلمه‌ی عبور
                </a>
            </div>
            <div class="menu-item px-5">
                <a class="menu-link px-5" asp-controller="Login" asp-action="LogOff"
                asp-area="@AreaConstants.DashboardArea">
                    خروج
                </a>
            </div>
        </div>
    }
</div>