Billiard-web/src/Billiard/Areas/Dashboard/Controllers/WalletController.cs
using DNTBreadCrumb.Core;
using DNTCommon.Web.Core;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Billiard.Common.GuardToolkit;
using Billiard.Entities;
using Billiard.paapCWallet;
using Billiard.Services;
using Billiard.Services.Identity;
using Billiard.ViewModels;
using Billiard.ViewModels.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using QRCoder;
using System.Drawing.Imaging;

namespace Billiard.Areas.Dashboard.Controllers
{
    [Area(AreaConstants.DashboardArea)]
    [Authorize(Policy = ConstantPolicies.DynamicPermission)]
    [BreadCrumb(Title = "کیف پول ها", UseDefaultRouteUrl = true, Order = 0)]
    [DisplayName("کیف پول ها")]

    public class WalletController : Controller
    {
        private readonly IWalletBilliardServices _walletBilliardManager;
        public WalletController(IWalletBilliardServices walletBilliardManager)
        {
            _walletBilliardManager = walletBilliardManager;
        }
        private int DefaultPageSize = 10;

        [BreadCrumb(Title = "لیست کیف پول ها", Order = 1)]
        [DisplayName("لیست کیف پول ها")]

        public IActionResult Index()
        {
            return View();
        }


        [BreadCrumb(Title = "کیف پول تومان", Order = 1)]
        [DisplayName("کیف پول تومان")]

        public IActionResult Toman()
        {
            return View();
        }

        [BreadCrumb(Title = "کیف پول وبمانی", Order = 1)]
        [DisplayName("کیف پول وبمانی")]

        public IActionResult WebMoney()
        {
            return View();
        }


        [BreadCrumb(Title = "کیف پول سناتور", Order = 1)]
        [DisplayName("کیف پول سناتور")]

        public IActionResult Billiard(int page = 1)
        {

            var userId = this.User.Identity.GetUserId<int>();
            var allAccount = _walletBilliardManager.Query(c => c.UserId == userId).OrderBy(c => c.OrderByDescending(z => z.CreatedDateTime)).SelectPage(page, DefaultPageSize, out int TotalItems).ToList();


            var model = new PagedListViewModel<WalletBilliardViewModel>();
            var _list = new List<WalletBilliardViewModel>();
            foreach (var item in allAccount.ToList())
            {
                var Secret = TextEncryptDecrypt.DecryptCipherTextToPlainText(item.Account);
                BilliardService account = new BilliardService(Secret);
                _list.Add(new WalletBilliardViewModel()
                {
                    Address = account.GetAddress(),
                    Amount = account.GetBalance(),
                    Name = item.Name,
                    Id = item.Id
                });
            }
            model.List = _list;
            model.Paging.TotalItems = TotalItems;
            model.Paging.CurrentPage = page;
            model.Paging.ItemsPerPage = DefaultPageSize;
            model.Paging.ShowFirstLast = true;
            return View(model);

        }




        [AjaxOnly]
        public IActionResult AddWalletBilliard()
        {
            var userId = this.User.Identity.GetUserId<int>();

            var model = new AddBilliardWalletViewModel();
            Account account = new Account();
            _walletBilliardManager.InsertAsync(new WalletBilliard()
            {
                Account = TextEncryptDecrypt.EncryptPlainTextToCipherText(account.SecretNumber.ToString()),
                Name = "",
                UserId = userId

            });
            model.Address = account.GetAddress();
            model.PubKey = account.GetPubKeyHex();
            model.SecretNumber = account.SecretNumber.ToString();

            return PartialView("_ResultAddBilliardWallet", model);
        }

        [HttpGet]
        public IActionResult GetQRCode(String text)
        {
            QRCodeGenerator qrGenerator = new QRCodeGenerator();
            QRCodeData qrCodeData = qrGenerator.CreateQrCode(text, QRCodeGenerator.ECCLevel.Q);
            QRCode qrCode = new QRCode(qrCodeData);
            System.Drawing.Bitmap qrCodeImage = qrCode.GetGraphic(20);
            return File(BitmapToBytes(qrCodeImage), "image/jpeg");
        }
        private static Byte[] BitmapToBytes(System.Drawing.Bitmap img)
        {
            using (MemoryStream stream = new MemoryStream())
            {
                img.Save(stream,ImageFormat.Png);
                return stream.ToArray();
            }
        }
    }
}

Billiard-web/src/Billiard/Controllers/MessagesController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Billiard.Controllers
{
    public class MessagesController : Controller
    {
        private NotificationsMessageHandler _notificationsMessageHandler { get; set; }

        public MessagesController(NotificationsMessageHandler notificationsMessageHandler)
        {
            _notificationsMessageHandler = notificationsMessageHandler;
        }

        [HttpGet]
        public async Task SendMessage([FromQueryAttribute]string message)
        {
           await _notificationsMessageHandler.SendMessageToAllAsync(message);
        }
    }
}

Billiard-web/src/Billiard/Areas/Dashboard/Views/Wallet/Billiard.cshtml
@model PagedListViewModel<WalletBilliardViewModel>
@{
    ViewData["Title"] = "کیف پول سناتور";
}
<div class="card mb-5 mb-xl-10">
    <div class="card-body pt-9 pb-0">
        <div class="d-flex flex-wrap flex-sm-nowrap mb-3">

            <div class="flex-grow-1">
                <div class="d-flex justify-content-between align-items-start flex-wrap mb-2">
                    <div class="d-flex flex-column">
                        <div class="d-flex align-items-center mb-2">
                            <div class="symbol symbol-25px symbol-lg-25px symbol-fixed position-relative ml-10">
                                <img src="/theme/Desktop/assets/media/wallet/Billiard-wallet-Billiard.png" alt="Billiard" />
                            </div>
                            <a class="text-gray-800 text-hover-primary fs-2 fw-bolder me-1" asp-controller="Wallet"
                                asp-action="Billiard" asp-area="@AreaConstants.DashboardArea">
                                کیف پول سناتور
                            </a>
                        </div>
                    </div>
                </div>
                <div class="d-flex flex-wrap flex-stack">
                    <div class="d-flex flex-column flex-grow-1 pe-8">
                        <div class="d-flex flex-wrap">
                            <div class="border border-gray-300 border-dashed rounded  py-3 px-4 me-6 mb-3">
                                <div class="d-flex align-items-center">
                                    <div class="fs-2 fw-bolder" data-ppc-countup="true" data-ppc-countup-value="13569">0
                                    </div>
                                </div>
                                <div class="fw-bold fs-6 text-gray-400">موجودی کلی</div>
                            </div>
                            <div class="border border-gray-300 border-dashed rounded  py-3 px-4 me-6 mb-3">
                                <div class="d-flex align-items-center">
                                    <div class="fs-2 fw-bolder" data-ppc-countup="true" data-ppc-countup-value="13400">0
                                    </div>
                                </div>
                                <div class="fw-bold fs-6 text-gray-400"> موجودی قابل برداشت</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="d-flex overflow-auto h-55px">
            <ul class="nav nav-stretch nav-line-tabs nav-line-tabs-2x border-transparent fs-5 fw-bolder flex-nowrap"
                id="myTab">
                <li class="nav-item">
                    <a class="nav-link text-active-primary me-6" data-ppc-countup-tabs="true" data-bs-toggle="tab"
                        href="#addwallet-Billiard">افزودن کیف پول</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link text-active-primary me-6" data-ppc-countup-tabs="true" data-bs-toggle="tab"
                        href="#mng-Billiard">مدیریت | دریافت</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link text-active-primary me-6" data-ppc-countup-tabs="true" data-bs-toggle="tab"
                        href="#send-Billiard">ارسال</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-active-primary me-6" data-ppc-countup-tabs="true" data-bs-toggle="tab"
                        href="#buy-Billiard">خرید</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link text-active-primary me-6" data-ppc-countup-tabs="true" data-bs-toggle="tab"
                        href="#transaction-Billiard">تراکنش ها</a>
                </li>

            </ul>
        </div>
    </div>
</div>
<div class="tab-content">

    <div class="card mb-5 mb-xl-10 tab-pane fade" id="addwallet-Billiard" role="tabpanel">
        <div class="card-header cursor-pointer">
            <div class="card-title m-0">
                <h3 class="fw-bolder m-0">افزودن کیف پول</h3>
            </div>
        </div>
        <div class="card-body p-9">

            <div class="row g-9 mb-3" data-kt-buttons="true" data-kt-buttons-target="[data-kt-button]">

                <div class="col-6">


                    <a href="" class="menu-link px-3" data-ajax-method="POST" data-ajax="true"
                        data-ajax-url="@Url.Action("AddWalletBilliard","Wallet")" data-ajax-update="#ResultPanel">

                        <label
                            class="btn btn-outline btn-outline-dashed btn-outline-default d-flex flex-column text-start p-6"
                            data-kt-button="true">

                            <span class="d-flex mb-2">

                                <span class="form-check form-check-custom form-check-solid form-check-sm me-5">
                                    <input class="form-check-input" type="radio"
                                        name="layout-builder[layout][illustrations][set]" value="addWallet">
                                </span>


                                <span class="fs-4 fw-bolder">افزودن کیف پول جدید</span>

                            </span>


                            <span style="background-image:url('/theme/Desktop/assets/media/illustrations/coding.png')"
                                class="d-block h-200px w-100 bgi-no-repeat bgi-size-contain bgi-position-center"></span>

                        </label>
                    </a>
                </div>


                <div class="col-6">

                    <label
                        class="btn btn-outline btn-outline-dashed btn-outline-default d-flex flex-column text-start p-6"
                        data-kt-button="true">

                        <span class="d-flex mb-2">

                            <span class="form-check form-check-custom form-check-solid form-check-sm me-5">
                                <input class="form-check-input" type="radio"
                                    name="layout-builder[layout][illustrations][set]" value="recoverWallet">
                            </span>


                            <span class="fs-4 fw-bolder">بازیابی کیف پول</span>

                        </span>


                        <span style="background-image:url('/theme/Desktop/assets/media/illustrations/presentation.png')"
                            class="d-block h-200px w-100 bgi-no-repeat bgi-size-contain bgi-position-center"></span>

                    </label>

                </div>

            </div>

            <div class="row" id="ResultPanel">

            </div>
        </div>

    </div>


    <div class="card mb-5 mb-xl-10 tab-pane fade" id="mng-Billiard" role="tabpanel">
        <div class="card-header cursor-pointer">
            <div class="card-title m-0">
                <h3 class="fw-bolder m-0">مدیریت | دریافت</h3>
            </div>
        </div>
        <div class="card-body p-9">

            <div id="gridcontainer" class="mt-5">
                <partial name="_BilliardWalletList" model="Model" />
            </div>

        </div>

    </div>


    <div class="card mb-5 mb-xl-10 tab-pane fade" id="buy-Billiard" role="tabpanel">
        <div class="card-header cursor-pointer">
            <div class="card-title m-0">
                <h3 class="fw-bolder m-0">خرید سناتور</h3>
            </div>
        </div>
        <div class="card-body p-9">

   

        </div>

    </div>

</div>

@section Style
{

<link href="~/lightbox/css/lightbox.min.css" rel="stylesheet" />

}



@section Scripts
{
<script src="~/lightbox/js/lightbox.min.js"></script>
}

Billiard-web/src/Billiard/Areas/Dashboard/Views/Wallet/Index.cshtml
<div class="overflow-auto pb-5">
    <div
        class="notice d-flex bg-light-primary rounded border-primary border border-dashed min-w-lg-600px flex-shrink-0 p-6">
        <span class="svg-icon svg-icon-2tx svg-icon-primary me-4">
            <svg xmlns="http://www.w3.org/2000/svg" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                <path
                    d="M6,7 C7.1045695,7 8,6.1045695 8,5 C8,3.8954305 7.1045695,3 6,3 C4.8954305,3 4,3.8954305 4,5 C4,6.1045695 4.8954305,7 6,7 Z M6,9 C3.790861,9 2,7.209139 2,5 C2,2.790861 3.790861,1 6,1 C8.209139,1 10,2.790861 10,5 C10,7.209139 8.209139,9 6,9 Z"
                    fill="#000000" fill-rule="nonzero"></path>
                <path
                    d="M7,11.4648712 L7,17 C7,18.1045695 7.8954305,19 9,19 L15,19 L15,21 L9,21 C6.790861,21 5,19.209139 5,17 L5,8 L5,7 L7,7 L7,8 C7,9.1045695 7.8954305,10 9,10 L15,10 L15,12 L9,12 C8.27142571,12 7.58834673,11.8052114 7,11.4648712 Z"
                    fill="#000000" fill-rule="nonzero" opacity="0.3"></path>
                <path
                    d="M18,22 C19.1045695,22 20,21.1045695 20,20 C20,18.8954305 19.1045695,18 18,18 C16.8954305,18 16,18.8954305 16,20 C16,21.1045695 16.8954305,22 18,22 Z M18,24 C15.790861,24 14,22.209139 14,20 C14,17.790861 15.790861,16 18,16 C20.209139,16 22,17.790861 22,20 C22,22.209139 20.209139,24 18,24 Z"
                    fill="#000000" fill-rule="nonzero"></path>
                <path
                    d="M18,13 C19.1045695,13 20,12.1045695 20,11 C20,9.8954305 19.1045695,9 18,9 C16.8954305,9 16,9.8954305 16,11 C16,12.1045695 16.8954305,13 18,13 Z M18,15 C15.790861,15 14,13.209139 14,11 C14,8.790861 15.790861,7 18,7 C20.209139,7 22,8.790861 22,11 C22,13.209139 20.209139,15 18,15 Z"
                    fill="#000000" fill-rule="nonzero"></path>
            </svg>
        </span>

        <div class="d-flex flex-stack flex-grow-1 flex-wrap flex-md-nowrap">
            <div class="mb-3 mb-md-0 fw-bold">
                <h4 class="text-gray-800 fw-bolder">کیف پول های سناتور</h4>
                <div class="fs-6 text-gray-600 pe-7">دارایی خود را در کیف پول های سناتور نگهداری کنید</div>
            </div>
            <a href="#" class="btn btn-primary px-6 align-self-center text-nowrap">کسب درآمد از سناتور</a>
        </div>
    </div>
</div>

<div class="row g-6 g-xl-9">
    <div class="col-md-6 col-xxl-4">
        <div class="card">
            <div class="card-body d-flex flex-center flex-column pt-12 p-9">
                <div class="symbol symbol-65px symbol-circle mb-5">
                    <img src="/theme/Desktop/assets/media/wallet/Billiard-wallet-usdt-trc20.png" alt="image">
                </div>
                <a asp-controller="Wallet" asp-action="Toman" asp-area="@AreaConstants.DashboardArea"
                    class="fs-4 text-gray-800 text-hover-primary fw-bolder mb-0">کیف پول تتر - TRC-20</a>
                <div class="fw-bold text-gray-400 mb-6"></div>
                <div class="d-flex flex-center flex-wrap">
                    <div class="border border-gray-300 border-dashed rounded min-w-80px py-3 px-4 mx-2 mb-3">
                        <div class="fs-6 fw-bolder text-gray-700"> 0 تتر</div>
                        <div class="fw-bold text-gray-400">موجودی کامل</div>
                    </div>

                    <div class="border border-gray-300 border-dashed rounded min-w-80px py-3 px-4 mx-2 mb-3">
                        <div class="fs-6 fw-bolder text-gray-700">0 تتر</div>
                        <div class="fw-bold text-gray-400">موجودی قابل برداشت</div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="col-md-6 col-xxl-4">
        <div class="card">
            <div class="card-body d-flex flex-center flex-column pt-12 p-9">
                <div class="symbol symbol-65px symbol-circle mb-5">
                    <img src="/theme/Desktop/assets/media/wallet/Billiard-wallet-usdt-erc20.png" alt="image">
                </div>
                <a asp-controller="Wallet" asp-action="WebMoney" asp-area="@AreaConstants.DashboardArea"
                    class="fs-4 text-gray-800 text-hover-primary fw-bolder mb-0">کیف پول تتر ERC-20</a>
                <div class="fw-bold text-gray-400 mb-6"></div>
                <div class="d-flex flex-center flex-wrap">
                    <div class="border border-gray-300 border-dashed rounded min-w-80px py-3 px-4 mx-2 mb-3">
                        <div class="fs-6 fw-bolder text-gray-700"> 0 تتر</div>
                        <div class="fw-bold text-gray-400">موجودی کامل</div>
                    </div>

                    <div class="border border-gray-300 border-dashed rounded min-w-80px py-3 px-4 mx-2 mb-3">
                        <div class="fs-6 fw-bolder text-gray-700">0 تتر</div>
                        <div class="fw-bold text-gray-400">موجودی قابل برداشت</div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-6 col-xxl-4">
        <div class="card">
            <div class="card-body d-flex flex-center flex-column pt-12 p-9">
                <div class="symbol symbol-65px symbol-circle mb-5">
                    <img src="/theme/Desktop/assets/media/wallet/Billiard-wallet-Billiard.png" alt="image">
                </div>
                <a asp-controller="Wallet" asp-action="Billiard" asp-area="@AreaConstants.DashboardArea"
                    class="fs-4 text-gray-800 text-hover-primary fw-bolder mb-0">کیف پول سناتور</a>
                <div class="fw-bold text-gray-400 mb-6"></div>
                <div class="d-flex flex-center flex-wrap">
                    <div class="border border-gray-300 border-dashed rounded min-w-80px py-3 px-4 mx-2 mb-3">
                        <div class="fs-6 fw-bolder text-gray-700"> 0 PPC</div>
                        <div class="fw-bold text-gray-400">موجودی کامل</div>
                    </div>

                    <div class="border border-gray-300 border-dashed rounded min-w-80px py-3 px-4 mx-2 mb-3">
                        <div class="fs-6 fw-bolder text-gray-700">0 PPC</div>
                        <div class="fw-bold text-gray-400">موجودی قابل برداشت</div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @* <div class="col-md-6 col-xxl-4">
        <div class="card">
            <div class="card-body d-flex flex-center flex-column pt-12 p-9">
                <div class="symbol symbol-65px symbol-circle mb-5">
                    <img src="/theme/Desktop/assets/media/wallet/Billiard-wallet-bitcoin.jpg" alt="image">
                </div>
                <a asp-controller="Wallet" asp-action="Toman" asp-area="@AreaConstants.DashboardArea"
                    class="fs-4 text-gray-800 text-hover-primary fw-bolder mb-0">کیف پول بیتکوین</a>
                <div class="fw-bold text-gray-400 mb-6"></div>
                <div class="d-flex flex-center flex-wrap">
                    <div class="border border-gray-300 border-dashed rounded min-w-80px py-3 px-4 mx-2 mb-3">
                        <div class="fs-6 fw-bolder text-gray-700"> 0 بیتکوین</div>
                        <div class="fw-bold text-gray-400">موجودی کامل</div>
                    </div>

                    <div class="border border-gray-300 border-dashed rounded min-w-80px py-3 px-4 mx-2 mb-3">
                        <div class="fs-6 fw-bolder text-gray-700">0 بیتکوین</div>
                        <div class="fw-bold text-gray-400">موجودی قابل برداشت</div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="col-md-6 col-xxl-4">
        <div class="card">
            <div class="card-body d-flex flex-center flex-column pt-12 p-9">
                <div class="symbol symbol-65px symbol-circle mb-5">
                    <img src="/theme/Desktop/assets/media/wallet/Billiard-wallet-ethereum.png" alt="image">
                </div>
                <a asp-controller="Wallet" asp-action="WebMoney" asp-area="@AreaConstants.DashboardArea"
                    class="fs-4 text-gray-800 text-hover-primary fw-bolder mb-0">کیف پول اتریوم</a>
                <div class="fw-bold text-gray-400 mb-6"></div>
                <div class="d-flex flex-center flex-wrap">
                    <div class="border border-gray-300 border-dashed rounded min-w-80px py-3 px-4 mx-2 mb-3">
                        <div class="fs-6 fw-bolder text-gray-700"> 0 اتریوم</div>
                        <div class="fw-bold text-gray-400">موجودی کامل</div>
                    </div>

                    <div class="border border-gray-300 border-dashed rounded min-w-80px py-3 px-4 mx-2 mb-3">
                        <div class="fs-6 fw-bolder text-gray-700">0 اتریوم</div>
                        <div class="fw-bold text-gray-400">موجودی قابل برداشت</div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-6 col-xxl-4">
        <div class="card">
            <div class="card-body d-flex flex-center flex-column pt-12 p-9">
                <div class="symbol symbol-65px symbol-circle mb-5">
                    <img src="/theme/Desktop/assets/media/wallet/Billiard-wallet-cardano.jpg" alt="image">
                </div>
                <a asp-controller="Wallet" asp-action="Billiard" asp-area="@AreaConstants.DashboardArea"
                    class="fs-4 text-gray-800 text-hover-primary fw-bolder mb-0">کیف پول کاردانو</a>
                <div class="fw-bold text-gray-400 mb-6"></div>
                <div class="d-flex flex-center flex-wrap">
                    <div class="border border-gray-300 border-dashed rounded min-w-80px py-3 px-4 mx-2 mb-3">
                        <div class="fs-6 fw-bolder text-gray-700"> 0 کاردانو</div>
                        <div class="fw-bold text-gray-400">موجودی کامل</div>
                    </div>

                    <div class="border border-gray-300 border-dashed rounded min-w-80px py-3 px-4 mx-2 mb-3">
                        <div class="fs-6 fw-bolder text-gray-700">0 کاردانو</div>
                        <div class="fw-bold text-gray-400">موجودی قابل برداشت</div>
                    </div>
                </div>
            </div>
        </div>
    </div> *@

</div>

Billiard-web/src/Billiard/Areas/Dashboard/Views/Wallet/Tether.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Billiard-web/src/Billiard/Areas/Dashboard/Views/Wallet/WebMoney.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Billiard-web/src/Billiard/Areas/Dashboard/Views/Wallet/_Message.cshtml
@model AlertMessageViewModel
<script>
    $.bootstrapModalAlert({
        caption: '@Model.MessageTitle',
        body: '<div class="alert alert-@Model.MessageType"> <span class="bi bi-bell m-5" aria-hidden="true"></span>@Model.MessageText</div>'
    });
    setTimeout(function () {
        $('.modal').modal('hide');
        if (@Model.IsRefreshPage)
        {
            window.location.reload();
        }
    }, 2000);
</script>

Billiard-web/src/Billiard/Areas/Dashboard/Views/Wallet/_RecoverBilliardWallet.cshtml
@model RecoverBilliardWalletViewModel
<partial name="_CustomValidationSummary" />
<form asp-action="EditMobile" method="post">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">

                <h5 class="modal-title">بازیابی کیف پول</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>


            <div class="modal-body">
                <div class="form-group row mb-5">
                    <label asp-for="SecretNumber" class="col-md-3 col-form-label text-md-left"></label>
                    <div class="col-md-9">
                        <input asp-for="SecretNumber" class="form-control numEN"  dir="ltr"/>
                        <span asp-validation-for="SecretNumber" class="text-danger"></span>
                    </div>
                </div>
 
            </div>
            <div class="modal-footer">
                <button class="btn btn-primary" type="submit">بازیابی کیف پول</button>
                <button class="btn btn btn-secondary" data-bs-dismiss="modal" aria-hidden="true">انصراف</button>
            </div>
        </div>
    </div>
</form>

 

Billiard-web/src/Billiard/Areas/Dashboard/Views/Wallet/_ResultAddBilliardWallet.cshtml
@model AddBilliardWalletViewModel

<div class="row">

    <div class="notice d-flex bg-light-danger rounded border-danger border border-dashed p-6 mb-6">
        <span class="svg-icon svg-icon-2tx svg-icon-danger me-4">
            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px"
                height="24px" viewBox="0 0 24 24" version="1.1">
                <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                    <rect x="0" y="0" width="24" height="24"></rect>
                    <path
                        d="M4,4 L11.6314229,2.5691082 C11.8750185,2.52343403 12.1249815,2.52343403 12.3685771,2.5691082 L20,4 L20,13.2830094 C20,16.2173861 18.4883464,18.9447835 16,20.5 L12.5299989,22.6687507 C12.2057287,22.8714196 11.7942713,22.8714196 11.4700011,22.6687507 L8,20.5 C5.51165358,18.9447835 4,16.2173861 4,13.2830094 L4,4 Z"
                        fill="#000000" opacity="0.3"></path>
                    <path
                        d="M11.1750002,14.75 C10.9354169,14.75 10.6958335,14.6541667 10.5041669,14.4625 L8.58750019,12.5458333 C8.20416686,12.1625 8.20416686,11.5875 8.58750019,11.2041667 C8.97083352,10.8208333 9.59375019,10.8208333 9.92916686,11.2041667 L11.1750002,12.45 L14.3375002,9.2875 C14.7208335,8.90416667 15.2958335,8.90416667 15.6791669,9.2875 C16.0625002,9.67083333 16.0625002,10.2458333 15.6791669,10.6291667 L11.8458335,14.4625 C11.6541669,14.6541667 11.4145835,14.75 11.1750002,14.75 Z"
                        fill="#000000"></path>
                </g>
            </svg>
        </span>
        <div class="d-flex flex-stack flex-grow-1 flex-wrap flex-md-nowrap">
            <div class="mb-3 mb-md-0 fw-bold">
                <h4 class="text-gray-800 fw-bolder">
                    هشدار :
                </h4>
                <div class="fs-6 text-gray-600 pe-7">

                    <strong class="blogp">
                        رمز خصوصی خود را یادداشت کنید و آن را با کسی به اشتراک نگذارید. این رمز فقط یک بار به شما نمایش
                        داده میشود و در هیچ جا ذخیره نمیشود
                    </strong>
                </div>
            </div>

        </div>

    </div>

</div>

<div class="mb-10 fv-row fv-plugins-icon-container fv-plugins-bootstrap5-row-valid">

    <label class="form-label mb-3">آدرس کیف پول :</label>


    <input type="text" class="form-control form-control-lg form-control-solid numEN" name="Address" dir="ltr" placeholder=""
        value="@Model.Address">

</div>

<div class="mb-10 fv-row fv-plugins-icon-container fv-plugins-bootstrap5-row-valid">

    <label class="form-label mb-3">کلید عمومی :</label>


    <input type="text" class="form-control form-control-lg form-control-solid numEN" name="PubKey" dir="ltr" placeholder=""
        value="@Model.PubKey">

</div>

<div class="mb-10 fv-row fv-plugins-icon-container fv-plugins-bootstrap5-row-valid">

    <label class="form-label text-danger mb-3">رمز خصوصی :</label>


    <input type="text" class="form-control form-control-lg form-control-solid numEN" name="SecretNumber" dir="ltr" placeholder=""
        value="@Model.SecretNumber">

</div>

 